Using ivysettings.xml in application root.(Fixed version)

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -5,9 +5,6 @@
 BUILD_DIR=$1
 CACHE_DIR=$2
 
-echo "BUILD_DIR=$BUILD_DIR"
-echo "CACHE_DIR=$CACHE_DIR"
-
 PLAY_PATH=".play"
 IVY_PATH=".ivy2"
 
@@ -80,10 +77,12 @@ fi
 PLAY_SETTINGS_URL="http://s3.amazonaws.com/heroku-jvm-langpack-play/ivysettings.xml"
 
 echo -n "-----> Using ivysettings.xml in application root direcroty!"
-#if [ -f .ivy2/ivysettings.xml ]; then
-#rm .ivy2/ivysettings.xml 
-#fi
-#curl --silent --max-time 10 --location $PLAY_SETTINGS_URL --create-dirs --output .ivy2/ivysettings.xml
+if [ -f .ivy2/ivysettings.xml ]; then
+  # rm .ivy2/ivysettings.xml 
+  echo 'ivysettings.xml not found! Please commit .ivy2/ivysettings.xml in your application root directory.'
+  exit 1
+fi
+# curl --silent --max-time 10 --location $PLAY_SETTINGS_URL --create-dirs --output .ivy2/ivysettings.xml
 echo " done"
 
 # Build app
@@ -94,7 +93,6 @@ $PLAY_PATH/play version | sed -u 's/^/       /'
 APP_DIR=./
 echo "       Building Play! application at directory $APP_DIR"
 echo `pwd`
-cat ./.ivy2/ivysettings.xml
 DEPENDENCIES_CMD="$PLAY_PATH/play dependencies $APP_DIR --forProd --forceCopy --silent -Duser.home=$BUILD_DIR 2>&1"
 echo "       Resolving dependencies: $DEPENDENCIES_CMD"
 eval "$DEPENDENCIES_CMD" | sed -u 's/^/       /'
